PresseMots/PresseMots_Web/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;
using PresseMots_Web.Services;
using Vereyon.Web;

namespace PresseMots_Web.Controllers
{
    public class StoriesController : Controller
    {
        private IServiceBase<User> _userServices;
        private readonly IStoryService _service;

        public StoriesController(IStoryService service, IServiceBase<User> userService)
        {
            _userServices = userService;
            _service = service;
        }

        // GET: Stories/Index/
        public  IActionResult Index(int? Id)
        {            
            return View( Id == null? _service.GetAll() : _service.GetById(Id.Value));
        }

        public IActionResult SearchByTag(string tagName) {

            //Implantez le
            return View(nameof(Index), _service.SearchByTagName(tagName));


        }


        // GET: Stories/Create
        public IActionResult Create()
        {
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username");
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create([Bind("Title,Content,OwnerId")] Story story)
        {
            if (ModelState.IsValid)
            {
                _service.Create(story);

                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Edit/5
        public  IActionResult Edit(int id)
        {


            var story =  _service.GetById(id);
            if (story == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit([FromServices] HtmlSanitizer sanitizer, int id, [Bind("Id,Title,Content,Draft,OwnerId,CreationTime,LastEditTime,PublishTime")] Story story)
        {
            if (id != story.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                    _service.Edit(story);
             
                   return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Delete/5
        public  IActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Controllers/StoryTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;

namespace PresseMots_Web.Controllers
{
    public class StoryTagsController : Controller
    {
        private readonly IServiceBaseAsync<StoryTag> _service;
        private readonly IServiceBaseAsync<Story> _storyService;
        private readonly IServiceBaseAsync<Tag> _tagService;

        public StoryTagsController(IServiceBaseAsync<StoryTag> service, IServiceBaseAsync<Story> storyService, IServiceBaseAsync<Tag> tagService)
        {
            _service =service;
            _storyService = storyService;
            _tagService = tagService;
        }


  
        public async Task<IActionResult> Create(int storyId)
        {
            var story = await _storyService.GetByIdAsync(storyId);
            if (story == null)
            {
                return NotFound();
            }
            ViewBag.StoryTitle = story.Title;


            ViewData["TagId"] = new SelectList(await _tagService.GetAllAsync(), "Id", "Name");
            return View(new StoryTag() { Id=0, StoryId=storyId, TagId=0});
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StoryId,TagId")] StoryTag storyTag)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(storyTag);
                return RedirectToAction("Index", "Stories", new { Id = storyTag.StoryId});
            }

            var story = await _storyService.GetByIdAsync(storyTag.StoryId);
            if (story == null)
            {
                return NotFound();
            }
            ViewBag.StoryTitle = story.Title;

            ViewData["TagId"] = new SelectList(await _tagService.GetAllAsync(), "Id", "Name", storyTag.TagId);
            return View(storyTag);
        }

      

      


        public async Task<IActionResult> Delete(int id)
        {

            var storyTag = await _service.GetByIdAsync(id);
            
            return View(storyTag);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           var story = await _service.GetByIdAsync(id);
            await this._service.DeleteAsync(id);

            return RedirectToAction(nameof(Index), "Stories", new { Id=story.StoryId});
        }

  
    }
}

PresseMots/PresseMots_Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;

namespace PresseMots_Web.Controllers
{
    public class TagsController : Controller
    {
        private readonly IServiceBaseAsync<Tag> _service;

        public TagsController(IServiceBaseAsync<Tag> service)
        {
            _service = service;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
              return View(await _service.GetAllAsync());
        }

     

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(tag);
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

       

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            return View(await _service.GetByIdAsync(id));
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Views/StoryTags/Create.cshtml
@model PresseMots_DataModels.Entities.StoryTag

@{
    ViewData["Title"] = @Locals["Create"];
}

<h1>@Locals["Create"]</h1>

<h4>@Locals["Associate tag for"] @ViewBag.StoryTitle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StoryId" ></input>
            <div class="form-group">
                <label asp-for="TagId" class="control-label"></label> <a asp-action="Create" asp-controller="Tags" class="badge badge-secondary">@Locals["Add tag"]</a>
                <select asp-for="TagId" class ="form-control" asp-items="ViewBag.TagId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="@Locals["Add"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Locals["Back to List"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PresseMots/PresseMots_Web/Views/StoryTags/Delete.cshtml
@model PresseMots_DataModels.Entities.StoryTag

@{
    ViewData["Title"] = @Locals["Delete"];
}

<h1>@Locals["Delete"]</h1>

<h3>@Locals["Are you sure you want to delete this?"]</h3>
<div>
    <h4>@Locals["Tag Link"]</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Story)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Story.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Locals["Delete"]" class="btn btn-danger" /> |
          <a asp-action="Index" asp-controller="Stories" asp-route-Id="@Model.StoryId">@Locals["&laquo; Back"]</a>
    </form>
</div>