PresseMots/PresseMots_Web/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;
using PresseMots_Web.Services;
using Vereyon.Web;

namespace PresseMots_Web.Controllers
{
    public class StoriesController : Controller
    {
        private IServiceBase<User> _userServices;
        private readonly IStoryService _service;

        public StoriesController(IStoryService service, IServiceBase<User> userService)
        {
            _userServices = userService;
            _service = service;
        }

        // GET: Stories/Index/
        public  IActionResult Index(int? Id)
        {            
            return View( Id == null? _service.GetAll() : _service.GetById(Id.Value));
        }

        public IActionResult SearchByTag(string tagName) {

            //Implantez le
            return View(nameof(Index), _service.SearchByTagName(tagName));


        }


        // GET: Stories/Create
        public IActionResult Create()
        {
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username");
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create([Bind("Title,Content,OwnerId")] Story story)
        {
            if (ModelState.IsValid)
            {
                _service.Create(story);

                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Edit/5
        public  IActionResult Edit(int id)
        {


            var story =  _service.GetById(id);
            if (story == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit([FromServices] HtmlSanitizer sanitizer, int id, [Bind("Id,Title,Content,Draft,OwnerId,CreationTime,LastEditTime,PublishTime")] Story story)
        {
            if (id != story.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                    _service.Edit(story);
             
                   return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Delete/5
        public  IActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;

namespace PresseMots_Web.Controllers
{
    public class TagsController : Controller
    {
        private readonly IServiceBaseAsync<Tag> _service;

        public TagsController(IServiceBaseAsync<Tag> service)
        {
            _service = service;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
              return View(await _service.GetAllAsync());
        }

     

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(tag);
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

       

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            return View(await _service.GetByIdAsync(id));
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Views/Tags/Create.cshtml
@model PresseMots_DataModels.Entities.Tag

@{
    ViewData["Title"] = @Locals["Create"];
}

<h1>@Locals["Create"]</h1>

<h4>@Locals["Tag"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Locals["Create"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Locals["Back to List"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PresseMots/PresseMots_Web/Views/Tags/Index.cshtml
@model IEnumerable<PresseMots_DataModels.Entities.Tag>

@{
    ViewData["Title"] = @Locals["Index"];
}

<h1>@Locals["Tags"]</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">@Locals["Delete"]</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-action="Index" asp-controller="Stories">@Locals["&laquo; Back to the stories"]</a>
</p>