PresseMots/PresseMots_Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataModels.Entities;
using PresseMots_Utility;
using PresseMots_Web.Models;
using PresseMots_Web.Services;

namespace PresseMots_Web.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentService _service;

        public CommentsController(ICommentService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? storyId)
        {
            if (storyId == null) return RedirectToAction("Index", "Stories");
            var vm = await this._service.GetVMByStoryIdAsync(storyId.Value);
            return View(vm);
        }

 
        public IActionResult Create(int? storyId)
        {
            if (storyId == null) return RedirectToAction("Index", "Stories");
            return View(new Comment() { StoryId = storyId ?? 0 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,DisplayName,Rating,Content,StoryId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(comment);
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }


        public  async Task<IActionResult> Edit(int id) => View(await _service.GetByIdAsync(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public  async Task<IActionResult> Edit(int id, [Bind("Id,Email,DisplayName,Rating,Content,Hidden,StoryId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                await _service.EditAsync(comment);
                return RedirectToAction(nameof(Index),new { storyId=comment.StoryId });
            }
            return View(comment);
        }

        public async  Task<IActionResult> Delete(int id) => View(await _service.GetByIdAsync(id));
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  async Task<IActionResult> DeleteConfirmed(int id)
        {
            var storyId = await _service.GetByIdAsync(id);
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index), new { storyId=storyId});
        }

    }
}

PresseMots/PresseMots_Web/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;
using PresseMots_Web.Services;
using Vereyon.Web;

namespace PresseMots_Web.Controllers
{
    public class StoriesController : Controller
    {
        private IServiceBase<User> _userServices;
        private readonly IStoryService _service;

        public StoriesController(IStoryService service, IServiceBase<User> userService)
        {
            _userServices = userService;
            _service = service;
        }

        // GET: Stories/Index/
        public  IActionResult Index(int? Id)
        {            
            return View( Id == null? _service.GetAll() : _service.GetById(Id.Value));
        }

        public IActionResult SearchByTag(string tagName) {

            //Implantez le
            return View(nameof(Index), _service.SearchByTagName(tagName));


        }


        // GET: Stories/Create
        public IActionResult Create()
        {
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username");
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create([Bind("Title,Content,OwnerId")] Story story)
        {
            if (ModelState.IsValid)
            {
                _service.Create(story);

                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Edit/5
        public  IActionResult Edit(int id)
        {


            var story =  _service.GetById(id);
            if (story == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit([FromServices] HtmlSanitizer sanitizer, int id, [Bind("Id,Title,Content,Draft,OwnerId,CreationTime,LastEditTime,PublishTime")] Story story)
        {
            if (id != story.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                    _service.Edit(story);
             
                   return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_userServices.GetAll(), "Id", "Username", story.OwnerId);
            return View(story);
        }

        // GET: Stories/Delete/5
        public  IActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Controllers/StoryTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresseMots_DataAccess.Context;
using PresseMots_DataAccess.Services;
using PresseMots_DataModels.Entities;

namespace PresseMots_Web.Controllers
{
    public class StoryTagsController : Controller
    {
        private readonly IServiceBaseAsync<StoryTag> _service;
        private readonly IServiceBaseAsync<Story> _storyService;
        private readonly IServiceBaseAsync<Tag> _tagService;

        public StoryTagsController(IServiceBaseAsync<StoryTag> service, IServiceBaseAsync<Story> storyService, IServiceBaseAsync<Tag> tagService)
        {
            _service =service;
            _storyService = storyService;
            _tagService = tagService;
        }


  
        public async Task<IActionResult> Create(int storyId)
        {
            var story = await _storyService.GetByIdAsync(storyId);
            if (story == null)
            {
                return NotFound();
            }
            ViewBag.StoryTitle = story.Title;


            ViewData["TagId"] = new SelectList(await _tagService.GetAllAsync(), "Id", "Name");
            return View(new StoryTag() { Id=0, StoryId=storyId, TagId=0});
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StoryId,TagId")] StoryTag storyTag)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(storyTag);
                return RedirectToAction("Index", "Stories", new { Id = storyTag.StoryId});
            }

            var story = await _storyService.GetByIdAsync(storyTag.StoryId);
            if (story == null)
            {
                return NotFound();
            }
            ViewBag.StoryTitle = story.Title;

            ViewData["TagId"] = new SelectList(await _tagService.GetAllAsync(), "Id", "Name", storyTag.TagId);
            return View(storyTag);
        }

      

      


        public async Task<IActionResult> Delete(int id)
        {

            var storyTag = await _service.GetByIdAsync(id);
            
            return View(storyTag);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           var story = await _service.GetByIdAsync(id);
            await this._service.DeleteAsync(id);

            return RedirectToAction(nameof(Index), "Stories", new { Id=story.StoryId});
        }

  
    }
}

PresseMots/PresseMots_Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using PresseMots_DataAccess.Context;
using PresseMots_DataModels.Entities;
using PresseMots_Web.Models;
using PresseMots_Web.Services;

namespace PresseMots_Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _service;
        private readonly IStringLocalizer<UsersController> _localizer;

        public UsersController(IUserService service, IStringLocalizer<UsersController> localizer)
        {
            _service = service;
            _localizer = localizer;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int id)
        {      
            return View(_service.GetForDetailAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> DetailsSearch(int UserId, string SearchTerm, bool AuthoredOpened, bool LikedStoriesOpened, bool SharedStoriesOpened, bool LikeableStoriesOpened)
        {

            var model = await _service.GetForDetailAsync(UserId, SearchTerm);
            model.AuthoredOpened = AuthoredOpened;
            model.LikedStoriesOpened = LikeableStoriesOpened;
            model.SharedStoriesOpened = SharedStoriesOpened;
            model.LikeableStoriesOpened = LikeableStoriesOpened;

            return View("Details", model);

        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Email,Password,ConfirmPassword")] AddUserViewModel user)
        {


            if (ModelState.IsValid)
            {
                await _service.CreateAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
           
            return View(await _service.GetForEditAsync(id));
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Email,OldPassword,Password,ConfirmPassword")] EditUserViewModel user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }          


            if (ModelState.IsValid)
            {
                await _service.EditAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            return View(await _service.GetByIdAsync(id));
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

PresseMots/PresseMots_Web/Views/Stories/Create.cshtml
@model PresseMots_DataModels.Entities.Story

@{
    ViewData["Title"] = @Locals["Create"];
}

<h1>@Locals["Create"]</h1>

<h4>@Locals["Story"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CreationTime)
            @Html.HiddenFor(x => x.LastEditTime)
            @Html.HiddenFor(x => x.PublishTime)
            @Html.HiddenFor(x => x.Draft)








            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control summernote"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="@Locals["Create"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Locals["Back to List"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
            $(document).ready(function() {
  $('.summernote').summernote();
});
    
    </script>

}

PresseMots/PresseMots_Web/Views/Stories/Delete.cshtml
@model PresseMots_DataModels.Entities.Story

@{
    ViewData["Title"] = @Locals["Delete"];
}

<h1>@Locals["Delete"]</h1>

<h3>@Locals["Are you sure you want to delete this?"]</h3>
<div>
    <h4>@Locals["Story"]</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEditTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEditTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Draft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Draft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Locals["Delete"]" class="btn btn-danger" /> |
        <a asp-action="Index">@Locals["Back to List"]</a>
    </form>
</div>

PresseMots/PresseMots_Web/Views/Stories/Edit.cshtml
@model PresseMots_DataModels.Entities.Story

@{
    ViewData["Title"] = @Locals["Edit"];
}

<h1>@Locals["Edit"]</h1>

<h4>@Locals["Story"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreationTime" />
            <input type="hidden" asp-for="LastEditTime" />
            <input type="hidden" asp-for="PublishTime" />

            <div class=" form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control summernote" ></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Locals["Save"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Locals["Back to List"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
            $(document).ready(function() {
  $('.summernote').summernote();
});
    
    </script>
}

PresseMots/PresseMots_Web/Views/Stories/Index.cshtml
@using Vereyon.Web
@model IEnumerable<PresseMots_DataModels.Entities.Story>

@{
    ViewData["Title"] = @Locals["Index"];
    var sanitizer = HtmlSanitizer.SimpleHtml5Sanitizer();
     sanitizer.SanitizeCssClasses = false;
}




        @foreach (var item in Model)
        {
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2> @Html.DisplayFor(modelItem => item.Title) @Locals["par"]  <a asp-action="Details" asp-route-id="@item.OwnerId" asp-controller="Users">@Html.DisplayFor(modelItem => item.Owner.Username)</a></h2>

                    @if (item.PublishTime != null)
                    {

                        <div class="badge badge-light">
                            @Locals["Published on"] @Html.DisplayFor(modelItem => item.PublishTime)
                        </div>
                    }

                </div>
                <div class="card-text" >
                   <partial name="_tags" model="item"  /><hr/>

                            @Html.Raw(sanitizer.Sanitize(item.Content ?? string.Empty))
                </div>
                <div class="panel-footer">

                    <div class="badge badge-info">
                        @Locals["Created on"] @Html.DisplayFor(modelItem => item.CreationTime)
                    </div>
                    @if (item.CreationTime != null)
                    {
                        <div class="badge badge-dark">
                            @Locals["Edit on"] @Html.DisplayFor(modelItem => item.CreationTime)
                        </div>

                    }



                    <hr />
                    <a asp-action="Index" asp-route-storyId="@item.Id" asp-controller="Comments">@item.Comments.Where(x => !x.Hidden).Count() @Locals["comment{0}",@item.Comments.Where(x => !x.Hidden).Count()<=1?"":"s"]</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">@Locals["Edit"]</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">@Locals["Delete"]</a> |
                    <a asp-action="Create" asp-controller="StoryTags" asp-route-storyId="@item.Id" >@Locals["+ tag"]</a>
                </div>
            </div>
        </div>
        <br/>


       }


<p>
    <a asp-action="Create">@Locals["New story"]</a>
</p>